# Directories containing the data
data_root: 
  - '/data1/practical-sose23/castellvi/3D-Castellvi-Prediction/data/dataset-verse19'
  - '/data1/practical-sose23/castellvi/3D-Castellvi-Prediction/data/dataset-verse20'

# Types of data contained in the directories
data_types: 
  - 'rawdata'
  - 'derivatives'

# Types of images used
img_types: 
  - 'ct'
  - 'subreg'
  - 'cortex'

# Path to the masterlist file
master_list: '/data1/practical-sose23/castellvi/team_repo/3D-Castellvi-Prediction/src/dataset/VerSe_masterlist_V3.xlsx'


# Type of classification to be used
classification_type : "right_side"

# Different classes used in the Castellvi classification
castellvi_classes: 
  - '1a'
  - '1b'
  - '2a'
  - '2b'
  - '3a'
  - '3b'
  - '4'
  - '0'

# Name of the model to be used
model: 'densenet'


# Whether to use segmentation or not
use_seg: False

# Whether to convert seg mask to binary, if use_seg is True
use_bin_seg: False

# Whether to zero out the image parts not belonging to vertebrae
use_zero_out: False

# Whether to use weighted sampling for equal label probabilities
weighted_sample: True

# Phase of the project (train/test)
phase: 'train'

# Scheduler for adjusting the learning rate
scheduler : "ReduceLROnPlateau"

# Optimizer for training the model
optimizer : "AdamW"

# Initial learning rate for training
learning_rate: 0.001

# Weight decay for the optimizer
weight_decay: 0.0001

# Total number of iterations for training
total_iterations: 100

# Number of samples per batch
batch_size: 8

# Number of Data Loader Workers
num_workers: 0

# Interval for saving the model during training
save_intervals: 10

# Total number of training epochs
n_epochs: 150

# Path to a pretrained model to resume training from
resume_path: ''

# Directory to save the experimental results
experiments: '/data1/practical-sose23/castellvi/3D-Castellvi-Prediction/experiments/'

# Whether to use CUDA or not
no_cuda: False

# ID of the GPU to be used for training
gpu_id: '3'

# Number of devices to use for training
n_devices: 1


# Seed for generating random numbers
manual_seed: 1

# Number of classes for classification
# Binary classification : 2
# Castellvi classification : 8
# Multi-class classification : 5
# Right side classification : 3 --> 0., 1: 2a and 2b, 3: 3a and 3b
num_classes : 3

# Port number for any network operations
port : 6484