data_root: 
  - '/data1/practical-sose23/dataset-verse19'
  - '/data1/practical-sose23/dataset-verse20'
data_types: 
  - 'rawdata'
  - 'derivatives'
img_types: 
  - 'ct'
  - 'subreg'
  - 'cortex'
master_list: '/data1/practical-sose23/castellvi/team_repo/3D-Castellvi-Prediction/src/dataset/VerSe_masterlist.xlsx'
master_list_v2 : '/data1/practical-sose23/castellvi/team_repo/3D-Castellvi-Prediction/src/dataset/VerSe_masterlist_V2.xlsx'
binary_classification: True
castellvi_classes: 
  - '1a'
  - '1b'
  - '2a'
  - '2b'
  - '3a'
  - '3b'
  - '4'
  - '0'
use_seg: False
phase: 'train'
scheduler : "polynomial"
optimizer : "Adam"
learning_rate: 0.001
weight_decay: 0.0001
total_iterations: 100
batch_size: 16
save_intervals: 10
n_epochs: 200
resume_path: ''
experiments: '/data1/practical-sose23/castellvi/team_repo/3D-Castellvi-Prediction/experiments/'
no_cuda: False
gpu_id: '3'
n_devices: 1
model: 'densenet'
manual_seed: 1
num_classes : 2
port : 9336
